### ISSUE TITLE
When a field is not found, the change callback is not called

### ISSUE THREAD

**Issue by johnBgood** [kflorence/jquery-deserialize#31]
Hi ! 

Nice plugin but I guess it lacks a function :) 

I have some ajax loaded fields, so when I call deserialize they aren't found. Then the **change** callback isn't called.
1. Do you think I'd be possible either to add a new callback (e.g. `fieldNotFound(name, value)`)  , or to trigger the **change** callback even if the value is not found.
2. Another solution - cleaner I guess - would be to add an option `dynamicFields : [ 'name1, name2,...']` which contains all dynamic fields. 
   Then when the loading is complete you can use a callback to retur a map with these fields and their values : `{ 'name1' : "value1", ... }`

Thanks before for the great work ;) 

Jonathan

**Comment by kflorence** [comment]
@johnBgood Hello, glad you've found the plugin useful. I think what you're looking for is live event binding (see [.on()](http://api.jquery.com/on/))-- the `change` callback of deserialize is only called when the field is populated with a value, it isn't actually a bound event at all. Are you wanting to populate specific fields? Otherwise, you can just call `deserialize` again after your dynamic fields have loaded.

**Comment by kflorence** [comment]
PS: you can also update fields individually as they load, for example:

```javascript
$("[name=text]").deserialize("text=text")
```
